### ISSUE TITLE
分页抓取怎么实现？

### ISSUE THREAD

**Issue by daxiangxiaoyi** [jinshuai86/Spider#1]
分页抓取怎么实现？

**Comment by jinshuai86** [comment]
需要根据不同的网页实现相应的解析器， 这个项目里的解析器是Parse.java。  
举个例子，对于 https://www.qiushibaike.com/text/page/1/ 在解析这个URL时，可以获取关于分页那块HTML标签里其它页对应的URL，比如https://www.qiushibaike.com/text/page/2/  然后将这个URL放到调度器里，依次类推😄

**Comment by daxiangxiaoyi** [comment]
首次传进去的url是一个对吧？可以多个吗

**Comment by daxiangxiaoyi** [comment]
`    @Override
    public void build(Parser parser, Saver saver, Set<Seed> urls) {
        setTargetTaskNumbers();
        setDownloader(new HttpClientDownloader());
        setParser(parser);
        setSaver(saver);
        setScheduler(new PriorityQueueScheduler(targetTaskNumbers));
        setThreadPool();
        for (Seed url:urls) {
            addUrlSeed(url);
        }
        run();
    }`
我这样写有问题吗
